quiniela_main:
    resource: "@QuinielaMainBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
    
_demo:
    resource: "@SaadTaziGChartBundle/Resources/config/routing.yml"
    type:     yaml
    prefix:   /gchart