# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fdb9b14b728f40c786fc5dd0ab5a2401ff8c4ff4fbd6af2acdc3936b8be6e34058a1a98f5579040891b17861fc9c36191365cafa5b2bb085cb1cff74b7f02d57

test:
  secret_key_base: 102e9845722609fb585304a3b1183db56983ce8f860497c29034a7cafb563cd94825e089d16b7b2be70b5de253f79244b0d69bdf985144f53a66c6b83d440fd2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
