quiniela_main_homepage:
    path:     /hola/{name}
    defaults: { _controller: QuinielaMainBundle:Default:index }

quiniela_list_all_teams:
    path:    /view/AllTeams
    defaults: { _controller: QuinielaMainBundle:Default:allTeams }

quiniela_prediction:
    path:    /new/Prediction
    defaults: { _controller: QuinielaMainBundle:Default:newPrediction }