quiniela_main_homepage:
    path:     /hola/{name}
    defaults: { _controller: QuinielaMainBundle:Default:index }

quiniela_list_all_teams:
    path:    /view/AllTeams
    defaults: { _controller: QuinielaMainBundle:Default:allTeams }

quiniela_prediction:
    path:    /new/Prediction
    defaults: { _controller: QuinielaMainBundle:Default:newPrediction }

quiniela_general_table:
    path:   /view/GeneralTable
    defaults: { _controller: QuinielaMainBundle:Default:generalTable}
user_login:
    pattern:   /user/login
    defaults:  { _controller: QuinielaMainBundle:Default:login }

user_login_check:
    pattern:   /user/login_check

user_logout:
    pattern:   /user/logout