parameters:
#    quiniela_main.example.class: Quiniela\MainBundle\Example

services:
#    quiniela_main.example:
#        class: %quiniela_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    login_listener:
        class: Quiniela\MainBundle\Listener\LoginListener
        arguments: [@router]
        tags:
          - { name: kernel.event_listener, event: security.interactive_login }
          - { name: kernel.event_listener, event: kernel.response }